FROM python:3.13-alpine

WORKDIR /app
COPY app.py .
COPY requirements.txt .

RUN apk add --no-cache postgresql-client

RUN pip install --no-cache-dir -r requirements.txt
CMD ["flask", "run", "--host=0.0.0.0"]

