#Notice for future: verify order of dependencies between services (depends_on)
services:
  business_interface:
    build: ./services/business_interface
    ports:
      - "5001:5000"
    depends_on:
      - db
      - db_api
    volumes:
      - ./services/business_interface:/app  

  customer_interface:
    build: ./services/customer_interface
    ports:
      - "5002:5000"
    depends_on:
      - db
      - db_api
    volumes:
      - ./services/customer_interface:/app  

  db_api:
    build: ./services/db_api
    ports:
      - "5003:5000"
    env_file:
      - .env.dev
    depends_on:
      - db
    volumes:
      - ./services/db_api:/app 

  db:
    image: postgres:15
    env_file:
      - .env.dev  
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: