services:
  service_interface:
    build: ./service_interface
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - ./service_interface:/app  

  service_flask:
    build: ./service_flask
    ports:
      - "5002:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - ./service_flask:/app  

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: